version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container_yami
    environment:
      POSTGRES_USER: example_user
      POSTGRES_PASSWORD: example_password
      POSTGRES_DB: example_db
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
  